//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DigitPerceptron.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DLGDIGIPATTERNGENERATOR_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       130
#define IDR_MENU_MAINFRAME              130
#define IDD_DIALOG_DIGIT                131
#define IDD_DIALOG_VIZ                  133
#define IDR_MENU_PROJECTIONVIEW         166
#define IDC_EDIT_TESTINGOUTPUT          1000
#define IDC_EDIT_RESULT                 1001
#define IDC_DRAWING_REGION              1002
#define IDC_LIST_PATTERNS_CNT           1003
#define IDC_LIST_PATTERNS               1004
#define IDC_BUTTON_CLEARSCREEN          1005
#define IDC_EDIT1                       1006
#define IDC_DLGDIGIT_EDIT_DIGIT         1006
#define IDC_DRAWING_REGION_RESULT       1006
#define IDC_BUTTON_DIGITRECOGNITION     1007
#define IDC_PROGRESS_NNPROCESSING       1008
#define IDC_STATIC_MSE                  1009
#define IDC_VISUALIZATION_REGION        1010
#define IDC_STATIC_MSE2                 1010
#define IDC_STATIC_NNACCURACY           1010
#define IDC_ADD_CURRENTPATTERN          1011
#define IDC_RUN_NN_PROCESSING2          1012
#define IDC_RUN_NN_PROCESSING           1012
#define IDC_ADD_CURRENTPATTERN2         1013
#define IDC_REMOVE_SELECTEDPATTERN      1013
#define IDC_iputnode                    1014
#define IDC_NUM_INPUTNODE               1014
#define IDC_hiddennode                  1015
#define IDC_NUM_HIDDENNODE              1015
#define IDC_outputnode                  1016
#define IDC_NUM_OUTPUTNODE              1016
#define IDC_NUM_OUTPUTNODE2             1017
#define IDC_NEURAL_NETWORK              1017
#define IDC_DIGIT_PATTERN_FILE          1017
#define IDC_NUM_DIGIT                   1018
#define IDC_NUM_PATTERNS                1019
#define IDC_NUM_DIGIT2                  1020
#define IDC_NUM_ERROR_RATE              1020
#define IDC_STATIC_NNACCURACY2          1021
#define ID_FILE_LOAD                    32771
#define ID_FILE_EXIT                    32772
#define ID_HELP_ABOUT                   32774
#define ID_FILE_OPEN_PATTERN_DATA       32775
#define ID_FILE_SAVE_PATTERN_DATA       32776
#define ID_FILE_SAVEPATTERNFILE         32778
#define ID_VISUAL_REPRESENTATION        32779
#define ID_ANALYSIS_PCAINPUTDATA        32782
#define ID_PCAINPUTDATA_INPUTNODES      32783
#define ID_PCAINPUTDATA_INPUTANDHIDDENNODES 32784
#define ID_PCAINPUTDATA_INPUT           32785
#define ID_PCAINPUTDATA_INPUTHIDDENOUTPUT 32786
#define ID_PCAINPUTDATA_INPUTHIDDENOUTPUTNODES 32787
#define ID_POPUP_GLYPHSIZE              32788
#define ID_GLYPHSIZE_INCREASE           32789
#define ID_GLYPHSIZE_DECREASE           32790
#define ID_POPUP_SHOWLABEL              32791
#define ID_POPUP_PCOORDVIEW_CANCEL      32857
#define ID_POPUP_BOXPLOTBODYSTYLE_CLASSIC 32865
#define ID_POPUP_BOXPLOTBODYSTYLE_NOTCH 32866
#define ID_POPUP_SHOWBOXPLOT            32867
#define ID_POPUP_WHISKERSSTYLE_MINTOMAX 32868
#define ID_POPUP_WHISKERSSTYLE_TUKEY    32869
#define ID_POPUP_WHISKERSSTYLE_10TO90PERCENTILES 32870
#define ID_POPUP_WHISKERSSTYLE_5AND95PERCENTILES 32871
#define ID_POPUP_WHISKERSSTYLE_1AND99PERCENTILES 32873
#define ID_POPUP_WHISKERSSTYLE_2AND97PERCENTILES 32874
#define ID_POPUP_BOXPLOTBODYSTYLE_VIOLIN 32889
#define ID_POPUP_PCOORDVIEW_OPTIONS_SEPARATEBOXPLOT 32894
#define ID_POPUP_PCOORDVIEW_OPTIONS_CLASSICALBOXPLOT 32897
#define ID_POPUP_PROJECTIONVIEW_POPUPWINDOW 32906
#define ID_POPUP_PROJECTIONVIEW_SHOWBIPLOT 32908
#define ID_POPUP_PROJECTIONVIEW_PCPROJECTION_FLIPHORIZONTALLY 32912
#define ID_POPUP_PROJECTIONVIEW_PCPROJECTION_FLIPVERTICALLY 32913
#define ID_VISUALCOMPLEXITY_HIGHCOMPLEXITY 32929
#define ID_VISUALCOMPLEXITY_MANUALCOMPLEXITY 32930
#define ID_VISUALCOMPLEXITY_LOWCOMPLEXITY 32931
#define ID_VISUALCOMPLEXITY_MEDIUMCOMPLEXITY 32933

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32792
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
